### ISSUE TITLE
removed cradle dependency, other changes

### ISSUE THREAD

**Issue by ianshward** [tdebarochez/connect-couchdb#1]
Hello Thomas, I've got a fork of connect-couchdb here https://github.com/developmentseed/connect-couchdb w/ the largest change being a swap out of cradle for a much simpler couch library.  I've also added things like limiting the revisions on docs, since every page load may generate multiple revisions of a user's session document, and added compaction to keep the db size in check.   Are these changes you're interested in merging back into your branch?

**Comment by tdebarochez** [comment]
I'm not sure adding underscore and request dependencies are better than juste cradle, but you made a great job and I will looking for replace this deps by only nodejs utils.

Are you sure revisions are created on each page load ? Isn't every session's data modification ? If yes, it's ok for me to let's growing up database size with some revisions. Perhaps it could be an option.

**Comment by ianshward** [comment]
I've implemented _revs_limit as an option and put a default value in for compactInterval.  We're using connect-couchdb with [bones](https://github.com/developmentseed/bones) and under that application model several session get/set's could be fired per page load, each of which saves a revision to the database.  Specifically, the lastAccess value, at the least, is modified each time.

Underscore and request are # 1 and # 5 on the "Most Depended On" list here http://search.npmjs.org/ which is a good sign.  I think if we were to drop request then we'd end up re-implementing a lot of request w/in this module, which would be a disadvantage (wouldn't get the same amount of use/testing/support as request based on limited user base of connect-couchdb).

**Comment by tdebarochez** [comment]
I've you got some examples/test ? Your fork doesn't seems to work with old example.

**Comment by ianshward** [comment]
The difference is that you pass connect in as an argument to the module, which is related to [this issue on connect-redis](https://github.com/visionmedia/connect-redis/issues/23).  Based on this, you'd now do something like:

``` javascript
var connect = require('connect');
var connectCouchDB = require('connect-couchdb')(connect);
var server = connect.createServer(connect.cookieDecoder(),
        connect.session({secret: 'your secret passphrase',
        store: new connectCouchDB({name: "test"})}),
```

**Comment by tdebarochez** [comment]
Yes, it's what I did (it's just cookieParser, not cookieDecoder).

But, I still have an issue with data storage. What's Couchdb version used you ?

**Comment by ianshward** [comment]
Are you getting any specific errors?

**Comment by ianshward** [comment]
Version 1.0.1

**Comment by tdebarochez** [comment]
I'm using the 0.8 version, the default on my debian 5.
My error is in Couch#post(), the specified sid is not kept.
I'm going to write a test for that.

**Comment by ianshward** [comment]
That's a pretty old (2+ years) version.  I'm using 1.0.1 from Ubuntu 10.04 LTS backports.  _revs_limit endpoint is supported as of 0.8-incubating (stated here http://wiki.apache.org/couchdb/Compaction) which I believe is post 0.8.0 tag.  I don't see _revs_limit anywhere in the source code in http://svn.apache.org/viewvc/couchdb/tags/0.8.0/ but I do see it in http://svn.apache.org/viewvc/couchdb/tags/0.9.0/, for example here http://svn.apache.org/viewvc/couchdb/tags/0.9.0/src/couchdb/couch_db.erl?revision=757877&view=markup therefore https://github.com/developmentseed/connect-couchdb/blob/master/lib/connect-couchdb.js#L54 will fail.

**Comment by tdebarochez** [comment]
Ok, I've updated my distros and now the version is 0.11...
But it's seems to work better : all tests pass sucessfully
I still have this issue sometimes (with the example) : 

```
TypeError: Cannot read property 'tick' of undefined
    at Object.helloWorld [as handle] (/path/js/connect-couchdb/example.js:5:19)
    at next (/path/.node_libraries/connect/lib/http.js:204:15)
    at Object.session [as handle] (/path/.node_libraries/connect/lib/middleware/session.js:214:47)
    at next (/path/.node_libraries/connect/lib/http.js:204:15)
    at Object.cookieParser [as handle] (/path/.node_libraries/connect/lib/middleware/cookieParser.js:44:5)
    at next (/path/.node_libraries/connect/lib/http.js:204:15)
    at HTTPServer.handle (/path/.node_libraries/connect/lib/http.js:217:3)
    at HTTPServer.emit (events.js:67:17)
    at HTTPParser.onIncoming (http.js:1109:12)
    at HTTPParser.onHeadersComplete (http.js:108:31)
```

But I'm afraid it's a connect issue, I'm going to investigate in this way.

Thanks for your work.
